/*type Database = {
    [database: string]: [data_type_category:string, data_type:string][]
}*/

export const databases= {
    //https://www.w3schools.com/sql/sql_datatypes.asp
    mySQL:[
        ['character', 'char'],
        ['character','varchar'],
        ['character', 'binary'],
        ['character', 'varbinary'],
        ['character', 'tinyblob'],
        ['character', 'tinytext'],
        ['character', 'text'],
        ['character', 'blob'],
        ['character', 'medium'],
        ['character', 'mediumtext'],
        ['character', 'mediumblob'],
        ['character', 'longblob'],
        ['character', 'enum: look into'],
        ['character', 'set: notes'],
        ['numeric', 'bit'],
        ['numeric', 'tinyint'],
        ['numeric', 'bool'],
        ['numeric', 'smallint'],
        ['numeric', 'mediumint'],
        ['numeric', 'int'],
        ['numeric', 'bigint'],
        ['numeric', 'float'],
        ['numeric', 'double'],
        ['numeric', 'double precision'],
        ['numeric', 'dec'],
        ['date', 'date'],
        ['date', 'datetime'],
        ['date', 'timestamp'],
        ['date', 'time'],
        ['date', 'year']
    ],
    //https://www.postgresql.org/docs/9.5/datatype.html
    postgresql: [
        ['numeric', 'smallint'],
        ['numeric', 'integer'],
        ['numeric', 'bigint'],
        ['numeric', 'decimal'],
        ['numeric', 'numeric'],
        ['numeric', 'real'],
        ['numeric', 'double precision'],
        ['numeric', 'smallserial'],
        ['numeric', 'serial'],
        ['numeric', 'bigserial'],
        ['monetary', 'money'],
        ['character', 'varchar'],
        ['character', 'char'],
        ['character', 'text'],
        ['binary', 'bytea'],
        ['date', 'date'],
        ['date', 'timestamp'],
        ['date', 'time'],
        ['date', 'interval'],
        ['boolean', 'boolean'],
        ['enum', '????'],
        ['geometric', 'point'],
        ['geometric', 'line'],
        ['geometric', 'lseg'],
        ['geometric', 'box'],
        ['geometric', 'path'],
        ['geometric', 'polygon'],
        ['geometric', 'circle'],
        ['network address', 'cidr'],
        ['network address', 'inet'],
        ['network address', 'macaddr'],
        ['bit', 'bit']
    ]
}